### ISSUE TITLE
Pose Description Generation Model

### ISSUE THREAD

**Issue by sinanmut** [naver/posescript#12]
Hi, 
when I try to run the script demo_generative_caption.py I get an error related to pre-trained model. The model size is not matching. Is the code different than the given pre-trained model weights? 
Thanks a lot.

  `streamlit run generative_caption/demo_generative_caption.py -- --model_paths demo_generative_caption.py` 

error lines:
```
  File "/posescript/src/text2pose/generative_caption/evaluate_generative_caption.py", line 52, in load_model
    model.load_state_dict(ckpt['model'])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DescriptionGenerator:
	size mismatch for text_decoder.embedding.weight: copying a param with shape torch.Size([2158, 512]) from checkpoint, the shape in current model is torch.Size([2563, 512]).
	size mismatch for text_decoder.final_layer.weight: copying a param with shape torch.Size([2158, 512]) from checkpoint, the shape in current model is torch.Size([2563, 512]).
	size mismatch for text_decoder.final_layer.bias: copying a param with shape torch.Size([2158]) from checkpoint, the shape in current model is torch.Size([2563]).
```

**Comment by g-delmas** [comment]
Hi!

These layers are related to the vocabulary. It seems like the vocabulary you are using has 2563 tokens instead of the expected 2158 (see command in the [README.md](https://github.com/naver/posescript?tab=readme-ov-file#closed_book-generate-the-vocabulary) to generate the expected vocabulary). Did you maybe consider other text files when building the vocabulary?
