### ISSUE TITLE
evaluate module error

### ISSUE THREAD

**Issue by minjung98** [naver/posescript#14]
I have a question about the 'evalueate' module. 
When I run the code `bash generative_modifier/script_generative_modifier.sh 'train' <training phase: pretrain|finetune> <seed number>`, an error occurs in the file src/text2pose/evaluate.py at line 271 where it says `metric = evaluate.load(mname)`. The error is as follows: `AttributeError: module 'evaluate' has no attribute 'load'`. I suspect that because the Python file name 'evaluate.py' is the same as the module name 'evaluate', the import statement at line 17 of evaluate.py is importing the Python file itself rather than the module. Since there is no 'load' function in the Python file, that's probably why this error occurs. I'm curious if you have encountered this error before. Thank you for your prompt and courteous response previously.

**Comment by g-delmas** [comment]
I didn't run in this problem within the file evaluate.py itself. In my case, something similar happened when both the library `evaluate` and that file were imported in another file through `import text2pose.evaluate as evaluate`. Maybe there is another module in your environment called 'evaluate', or the problem comes from how the text2pose package was loaded as a module (making the file evaluate.py a module itself..., but I don't know if this is even possible).

Anyhow, one **quick fix** would be to replace `import evaluate` from line 17 to something like `import evaluate as evaluate_huggingface`, and to replace all `evaluate.` by `evaluate_huggingface.` in evaluate.py.

**Comment by minjung98** [comment]
I resolved the issue by renaming the 'evaluate.py' file to differentiate it from Hugging Face Evaluate. Your suggested solution seemed simpler, but either way, the problem is now solved. Thank you!
