### ISSUE TITLE
generative_modifier/script_generative_modifier.sh 'eval' error

### ISSUE THREAD

**Issue by minjung98** [naver/posescript#18]
Hello. I'm sorry to ask you another question. 
I am understanding this project thanks to your always thorough responses. Thank you.

When I run the command:
`bash generative_modifier/script_generative_modifier.sh 'eval' /home/minjung/posescript/experiments/ret_distilbert_dataPSA2ftPSH2/seed1/checkpoint_best.pth`

I encounter the following error:
```
Traceback (most recent call last):
  File "generative_modifier/evaluate_generative_modifier.py", line 366, in <module>
    ret = eval_model(args.model_path, dataset_version=args.dataset, split=args.split, pose_model_version=args.pose_generative_model, textret_model_version=args.textret_model, fid_version=args.fid)
  File "generative_modifier/evaluate_generative_modifier.py", line 92, in eval_model
    model, tokenizer_name = load_model(model_path, device)
  File "generative_modifier/evaluate_generative_modifier.py", line 49, in load_model
    model = FeedbackGenerator(text_decoder_name=text_decoder_name,
  File "/home/minjung/posescript/src/text2pose/generative_modifier/model_generative_modifier.py", line 29, in __init__
    self.comparison_module = ComparisonModule(inlatentD=encoder_latentD,
  File "/home/minjung/posescript/src/text2pose/generative_modifier/model_generative_modifier.py", line 91, in __init__
    self.tirg = TIRG(input_dim=[inlatentD, inlatentD], output_dim=outlatentD, out_l2_normalize=False)
  File "/home/minjung/posescript/src/text2pose/encoders/modules.py", line 112, in __init__
    nn.Linear(self.input_dim, self.output_dim))
  File "/home/minjung/.conda/envs/posefix/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 85, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```
Anyway, it seems that the evaluation results are being generated. However, in the evaluation of GT, random, auto_posefix-A_cap0, the avg_likelihood: [0,0] is appearing. I'm wondering if this is related to the above error.

**Comment by g-delmas** [comment]
Hello,

1. Based on the command,  I assume you were trying to evaluate one of the checkpoints I shared. It seems like you are not loading the right model. `ret_distilbert_dataPSA2ftPSH2` corresponds to a *retrieval* model, not to the model generating modifiers, which is instead called `modgen_CAtransfPFAHPP_dataPFAftPFH` (see correspondences [here](https://github.com/naver/posescript/blob/main/pretrained_models.md#references-in-shortname_2_model_pathtxt)).
2. Results are only generated for the "control metrics", which do not depend on the input model, and simply give an idea of the performance when the role of the generated text is played by:
    * **GT**: the ground-truth text (leading to n-gram metrics equal to 100, for instance)
    * **random**: one of the annotated texts, chosen at random (it's a human-written text, but not the one originally associated to the pose pair at stake)
    * **auto_posefix-A_cap0**: one of the ground-truth automatic texts (generated by the automatic pipeline, not by the model!)
    In this case, `avg_likelihood` is 0 because no text has been generated by the model, and the avg likelihood aggregates the probability of generating each token of the final text.

**Comment by minjung98** [comment]
Thank you for your response. I realized I made a mistake. I was trying to understand too many things at once, which caused some confusion. Now, I completely understand your answer.

However, this question is a bit different, and it might seem foolish, but in the training stage of this git repository, I understand there are 'pretrain' and 'finetune' phases.

```
ret_distilbert_dataPSA2ftPSH2    <GENERAL_EXP_OUTPUT_DIR>/ret_distilbert_dataPSA2ftPSH2/seed1/checkpoint_best.pth
modret_distilbert_dataPFAftPFH    <GENERAL_EXP_OUTPUT_DIR>/modret_distilbert_dataPFAftPFH/seed1/checkpoint_best.pth
gen_distilbert_dataPSA2ftPSH2    <GENERAL_EXP_OUTPUT_DIR>/gen_distilbert_dataPSA2ftPSH2/seed1/checkpoint_best.pth
b_gen_distilbert_dataPFAftPFH    <GENERAL_EXP_OUTPUT_DIR>/b_gen_distilbert_dataPFAftPFH/seed1/checkpoint_best.pth
capgen_CAtransfPSA2H2_dataPSA2ftPSH2    <GENERAL_EXP_OUTPUT_DIR>/capgen_CAtransfPSA2H2_dataPSA2ftPSH2/seed1/checkpoint_best.pth
modgen_CAtransfPFAHPP_dataPFAftPFH    <GENERAL_EXP_OUTPUT_DIR>/modgen_CAtransfPFAftPFH/seed1/checkpoint_best.pth 

```

![스크린샷 2024-06-23 오후 11 39 02](https://github.com/naver/posescript/assets/130021582/23066225-de27-459d-bf99-e2b3f5b1aff8)

As far as I know, the models initially set up like the ones above are pretrained models. 
**So, does running the 'pretrain' phase mean pretraining these already pretrained models again with the data presented in this paper?** 
**Also, are both the pretrained and fine-tuned models saved in the same path (experiment) as checkpoint_best.pth, overwriting each other?** From what I've checked, the output path is the same as the path where the models are loaded. Lastly, I would like to know **what the seed value means in this code.**

Thank you.

**Comment by minjung98** [comment]
Additionally, I would like to ask, as I understand it, for the generative_modifier task, **a scratch TransformerDecoder model is used as the text decoder instead of a pre-trained language model** like distilbert-base-uncased. Is my understanding correct? 
If I am correct, I would like to know whether the distilbert-base-uncased model, which was mentioned in the readme to be downloaded to posescript/tools/huggingface_models, is **used as the text decoder or if it is used in a different context**.

<img width="820" alt="스크린샷 2024-06-24 오전 12 38 47" src="https://github.com/naver/posescript/assets/130021582/40596f81-bfa6-46ce-9184-077bd140b04e">

**Comment by g-delmas** [comment]
Hello!

* I apologize for the confusion. In the main README, the "pretrained" models refer to the shared checkpoints, which can be used to run the demos, for instance. Perhaps I should call them "trained models" instead. Their training involve a pretraining stage (on the automatic texts), and a finetuning stage (on the human-written texts). So basically, you don't need to further train the shared models.
* The pretrained and finetuned models (as described in the point above) won't be saved in the same directory if you let the code create the saving directory itself, in particular because the path to the finetuned checkpoint  carries information about the training dataset (which is different at the pretraining and finetuning stages), as well as information about the pretrained model (with something like "_pretrained_modgen_CAtransfPFAHPP_dataPFA"). Besides, the "train model" (downloaded shared checkpoint) will not be overwritten, should you decide to train a new version of it from scratch, because by default, it is saved in a "special" directory, based on its nickname.
* The seed value is set to 1 here, but could be any number you like. It serves to "fix" the randomness in the process so as to empower reproducibility of the experiments. You can run multiple experiments with different seeds and average all results to get an idea of the method's robustness.
* In the text generation experiments of this repo, the text decoder is indeed trained from scratch, based on the vocabulary created by parsing all texts in the training set. The pre-trained language model distilbert-base-uncased is not used by the text decoder. However, we use it for token embedding in other tasks which require a text *en*coder. Note that you could still decide to use distilbert-base-uncased in the text decoder, to (1) define a word-piece tokenization & vocabulary, (2) embed words before feeding them to the transformer decoder, (3) decode words in the language modeling head. You would need to modify the current code to do so.

**Comment by minjung98** [comment]
Now I think I have a better understanding of the overall code for the modifier generation task of your project. Thank you for the thorough explanation.
