### ISSUE TITLE
How to generate descriptions for self data (RGB image).

### ISSUE THREAD

**Issue by zstarN70** [naver/posescript#3]
Excellent work, I tried to generate pose data of smplh format, but all failed. I don't know how does. Please help me to provide a workable process to generate pose descriptions for my data. Thanks!

**Comment by g-delmas** [comment]
Hello!

I'm not sure to understand what you want to do.
Could you please specify:

- what input and output you expect?
- the command line your ran but that failed?
- the error message you got?

Thanks!

**Comment by zstarN70** [comment]
I'm so sorry!

I want to generate 3D pose data(52*3) for my data(images or videos) at the same format as AMASS. I tried many approaches, but all failed. 

- Input : (image or video), Output : 3d pose data(AMASS format  52, 3).
- How does the process work?
- First, I obtained the 2d pose information via [openpose.](https://github.com/CMU-Perceptual-Computing-Lab/openpose.git) Then I got the 3d information via [smplify-x](https://github.com/vchoutas/smplify-x.git), but it is a _dict_. I don't know how to match it with (52, 3).
![1bededbc023aadd8e1ea72cb943f166f_](https://github.com/naver/posescript/assets/87968517/fd28d065-1957-4194-b28a-be9623dc84a8)

Hopefully my description is clear and I need your help desperately. Thanks!

**Comment by g-delmas** [comment]
Thank you for providing more details.
Unfortunately, we don't deal with image or video input data; we generate 3D poses based on text descriptions. I'm afraid your problem is not related to the PoseScript project but to the smplify-x project instead.

Maybe [this issue](https://github.com/vchoutas/smplify-x/issues/86) will be helpful to you.

Good luck!
