### ISSUE TITLE
How to generate description for other dataset (ex: Human3.6M)

### ISSUE THREAD

**Issue by PeiChiChen** [naver/posescript#8]
Hello, thanks for your excellent works.

In your method, given a human pose in SMPL format, model generates the description of the pose.
Is it possible to generate description for other dataset like Human3.6M?
I think it will work as long as I can fit the 3D keypoints to SMPL parameters. Is it correct?

I'm a beginner of human pose.  Very appreciate if you can provide some guidance.
Thanks a lot!

**Comment by g-delmas** [comment]
Hi!

If you are referring to the [trained generative model](https://github.com/naver/posescript/tree/main/src/text2pose/generative_caption) (which takes as input the 3D joint rotations in axis-angle representation) and wish to use it out of the box with the pretrained weights, you'll probably need to adapt the input the match the one of the model (ie. use SMPL-H joints). If you intend to retrain it yourself, you can try using your own kind of input.

If your are referring to the (procedural) [automatic captioning pipeline](https://github.com/naver/posescript/tree/main/src/text2pose/posescript#page_with_curl-generate-automatic-captions) (which takes as input 3D joint coordinates), you may not need to convert your data to SMPL format. You can use the 3D keypoints you have directly. Note that:
* you may need to adapt this function [here](https://github.com/naver/posescript/blob/ad894fc6ddcc0e834bfa2e66fa60aa4095d1ba39/src/text2pose/posescript/utils.py#L123) along with `ALL_JOINT_NAMES` to prepare the input coordinates correctly (note that *'left_middle2'* and *'right_middle2'*  are only needed to define joints representing more or less the whole hands; you don't specifically need them for the pipeline to work, as long as you find a way to define virtual "hand" joints). 
* you may want to tune [this dictionary](https://github.com/naver/posescript/blob/ad894fc6ddcc0e834bfa2e66fa60aa4095d1ba39/src/text2pose/posescript/captioning_data.py#L54), which defines all the thresholds for computing the posecodes. Depending on the size of the bodies at hand, you may want some different values. You can use the[ `select_poses_such_that` method from the `Posecode` class ](https://github.com/naver/posescript/blob/ad894fc6ddcc0e834bfa2e66fa60aa4095d1ba39/src/text2pose/posescript/posecodes.py#L126)to visualize a bit the results you get for different joint sets and thresholds.

I hope this helps!

**Comment by PeiChiChen** [comment]
Deeply appreciate your assistance ! 

What I want to do is as follows:
Given the 3D keypoint coordinates or SMPL parameters of a human pose, the model generates description of each body part respectively like:
- Head: (description)
- Left arm: (description)
- Right arm: (description)
......

I think in my case, **"Generate automatic captions"** is better since **"train generative model"** generates the sentence describing the whole pose, while **"Generate automatic captions"** seems provide posecodes for each body part respectively.

Thanks for your help again, I will try it! ^^

**Comment by g-delmas** [comment]
In this case, I believe you will have to filter posecodes for each body part before calling the `aggregate_posecodes` function [here](https://github.com/naver/posescript/blob/ad894fc6ddcc0e834bfa2e66fa60aa4095d1ba39/src/text2pose/posescript/captioning.py#L88). Perhaps you would also prefer to move the [bloc performing side-reversing](https://github.com/naver/posescript/blob/ad894fc6ddcc0e834bfa2e66fa60aa4095d1ba39/src/text2pose/posescript/captioning.py#L849) out of that function and place it right before to get symmetric posecodes both for the left and right body sides (otherwise, the descriptions would be biased towards the left body side).

Something else I forgot to mention: the pipeline expects "normalized" joint coordinates, ie. one needs to apply the appropriate rotation so that the hips are facing the camera. Basically, if you plot the T-pose, the avatar should be looking at you, with their left hand on the right of the screen (as it is the avatar's right).
