### ISSUE TITLE
Posemix

### ISSUE THREAD

**Issue by HYJ-EIS** [naver/posescript#9]
Where to get the posemix dataset, we have a problem running the Generate the vocabulary step：#posemix vocab

```
Traceback (most recent call last):
  File "vocab.py", line 216, in <module>
    with open(save_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'g:\\posefix\\posescript-main/data/posemix\\vocab_posemix_PS6193_PF6157.pkl'
```

**Comment by g-delmas** [comment]
Hi,

Could it be that the directory `g:\\posefix\\posescript-main/data/posemix` does not exist on your disk? You can create it from the shell with eg. `mkdir /posefix/posescript-main/data/posemix`, then run the script again to generate the vocabulary.

Also, please note that you don't need to generate the vocabulary files if you intend to use a model with the Distilbert token embeddings instead of the GloVe token embeddings.

**Comment by HYJ-EIS** [comment]
Following your suggestion, I created the posemix folder and put the required files in it .Then the problem was solved. Thank you so much!
